using TestProject.Common.DTO.ExecutionResult;
using TestProject.Common.Enums;
using System;
using System.Reflection;
using TestProject.SDK;

namespace TestProject.Generated.Tests.Evernote
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Provides an example how to run coded TestProject tests
	/// </summary>
	public class EvernoteRunner
	{
		public static string DevToken = "c5HvBiBf7jQNX_3S_qLypPeolYqz6t_uB6phQ8kiDYU1";
		public static AutomatedBrowserType Browser = AutomatedBrowserType.Chrome;
		public static StepExecutionResult RunOpennote()
		{
			using (var runner = new RunnerBuilder(DevToken).AsWeb(Browser).Build())
				return runner.Run(new Opennote(), true);
		}

		public static void Main(string[] args)
		{
			try
			{
				RunOpennote();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex);
			}
		}
	}
}